# Generated by Django 2.2.3 on 2020-03-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='inn',
            field=models.CharField(db_index=True, max_length=12),
        ),
    ]
